import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:ptcbjahid/data/models/deal_model.dart';
import 'package:ptcbjahid/presentation/app.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // 1. Init Hive
  await Hive.initFlutter();

  // 2. Register Adapter (Generated by build_runner)
  Hive.registerAdapter(DealDataAdapter());
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light,
      systemNavigationBarColor: Colors.transparent,
      systemNavigationBarIconBrightness: Brightness.dark,
    ),
  );

  // 3. LOCK ORIENTATION & RUN
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]).then((
    _,
  ) {
    runApp(const DesiDimeApp());
  });
}
